### GET Employees
GET http://localhost:4004/service/demo/Employees


### GET Departments
GET http://localhost:4004/service/demo/Departments


### GET Departments Expand Employees
GET http://localhost:4004/service/demo/Departments?$expand=employees


### GET Employees V2
GET http://localhost:4004/v2/service/demo/Employees


### GET Departments V2
GET http://localhost:4004/v2/service/demo/Departments


### GET Departments Expand Employees V2
GET http://localhost:4004/v2/service/demo/Departments?$expand=employees
